Module2 task1
htmlacademy-adaptive/1422495-pognali-25 pull request #2
Opened 2022-04-13 04:53 UTC by LiamStag

Сделал html разметку главной страницы

2022-04-14 12:03 UTC, feralist21 requested changes
Молодец, хорошо начал! Давай уберем небольшие проблемки в коде и закроем эту задачу.

2022-04-14 12:03 UTC, feralist21 commented on source/index.html
> +                <a class="page-nav__list-link"><span class="page-nav__list-transition-text">О сервисе</span></a>
В данном и подобных местах класть в ссылку тег span будет излишним. Достаточно оставить просто текст в ссылке.

2022-04-14 12:03 UTC, feralist21 commented on source/index.html
> +    <section class="promo page-header__content-wrapper page-header__content-wrapper--main">
Использовать элемент content-wrapper без блока page-header является недопустимым. Подумай как здесь можно оптимальнее написать.

2022-04-14 12:03 UTC, feralist21 commented on source/index.html
> +        <div class="promo__main-content-wrapper">
Подумай, пожалуйста, может здесь можно дать более лаконичное название для элемента?)

2022-04-14 12:03 UTC, feralist21 commented on source/index.html
> +    </div>
Кажется тут что то пошло не так с дивами. Разберись, пожалуйста)

2022-04-15 16:30 UTC, LiamStag commented on source/index.html
> +                <a class="page-nav__list-link"><span class="page-nav__list-transition-text">О сервисе</span></a>
Убрал тег span, кроме тех, что с классом visually-hidden.

2022-04-16 15:07 UTC, feralist21 approved these changes
Все хорошо!

2022-04-16 15:08 UTC, merged